model_parameters:
  onnx_model: 'output/face_landmark.onnx'
  march: 'bayes-e'
  working_dir: 'horizon_output'
  output_model_file_prefix: 'face_landmark_bpu'

input_parameters:
  input_name: 'input_1'
  input_shape: '1,192,192,3'
  input_type_rt: 'nv12'
  input_type_train: 'rgb'
  input_layout_train: 'NHWC'
  input_layout_rt: 'NHWC'
  norm_type: 'data_scale'
  mean_value: 127.5
  scale_value: 127.5

calibration_parameters:
  cal_data_type: 'float32'
  calibration_type: 'default'

compiler_parameters:
  compile_mode: 'latency'
  optimize_level: 'O3'
